server:
  port: 8080

spring:
  application:
    name: msdeverton
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/msdeverton?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 34773132
